// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeService() *Service {
	iRepository := NewCRepository()
	service := NewServiceWire(iRepository)
	return service
}
